language: r
warnings_are_errors: true

r_binary_packages:
  - rgdal
  - rmarkdown

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: hjEnI9l76hZLl20BRpcdRnZ+eAxoSRNkA73Z30epv3ExYgQ8BNwKwiZsEOxKG1Zdfn61H6BS79MBImF6C9uEzHFgmj2uEnpISed/G7RAl7nsm8F9/8QSuKN1FIC23XmhhVg7oIPs136NAhf8vuA9ylqi6GW0MjO3AiPprf+XvlI=
